library(tidyverse)
library(rvest)

people <- read_html("https://taskmaster.fandom.com/wiki/Contestants") |>
  html_elements("td a") |>
  html_text2() |>
  str_subset("^[A-Z]") |>
  c("Alex Horne", "Greg Davies", "Fred the Swede")

series <- paste0("https://taskmaster.fandom.com/wiki/Series_", 1:19)
episodes <- map(series, \(x) {
  read_html(x) |>
    html_elements("td > span > a") |>
    html_attr("href")
}) |>
  unlist() |>
  str_subset("/wiki/") |>
  str_replace("/wiki/", "https://taskmaster.fandom.com/wiki/")

eps_html <- map(episodes, read_html)

titles <- map_chr(eps_html, \(x) {
  html_element(x, ".mw-page-title-main") |>
    html_text()
}) |>
  str_remove("\\.$")

title_chars <- map_chr(eps_html, \(x) {
  html_element(x, "h2+ p") |>
    html_text()
}) |>
  str_extract(str_c(people, collapse = "|"))

title_pairs <- tibble(quote = titles, name = title_chars) |>
  filter(!is.na(name))

tribble(
  ~"quote"                                                                                                              , ~"name"                                    ,
  "It's a shame that my hands aren't my feet."                                                                          , "Katherine Parkinson"                      ,
  "I guess the problem is that time only has two hands."                                                                , "Charlotte Richie"                         ,
  "He's sitting under a tree, thinking of tasks and shit."                                                              , "Jamali Maddix"                            ,
  "What else goes on a head?"                                                                                           , "Sarah Kendall"                            ,
  "Ah, you fucking zebra!"                                                                                              , "Sarah Kendall"                            ,
  "Stop doing the thing I know you're doing!"                                                                           , "Desiree Burch"                            ,
  "Oh come on, twenty seconds to give a man a soul?"                                                                    , "Alan Davies"                              ,
  "Do you stop when it's finished, or when you've had enough?"                                                          , "Alan Davies"                              ,
  "You stay or I'll smash you to pieces."                                                                               , "Bridget Christie"                         ,
  "Just imagine if you don't do this, someone will take my cats."                                                       , "Bridget Christie"                         ,
  "It's floating like two dicks."                                                                                       , "Judi Love"                                ,
  "Is balloon juice a thing?"                                                                                           , "Chris Ramsey"                             ,
  "Lotta pie."                                                                                                          , "Roisin Conaty"                            ,
  "If I had my chance again, I would have blown on his lips."                                                           , "Tim Key"                                  ,
  "I'm not an egg man."                                                                                                 , "Doc Brown"                                ,
  "The bastard's cryin', innit?"                                                                                        , "Paul Chowdry"                             ,
  "Camouflage, camouflage, camouflage."                                                                                 , "Lolly Adefope"                            ,
  "Not enough to sting, just enough to make you think."                                                                 , "Tim Vine"                                 ,
  "Will you catch my potato?"                                                                                           , "Liza Tarbuck"                             ,
  "H. Urinating. Piss."                                                                                                 , "Asim Chaudhry"                            ,
  "I can't be fucked to plug it in."                                                                                    , "Kerry Godliman"                           ,
  "How much does water weigh?"                                                                                          , "Jessica Knappet"                          ,
  "A LIME!"                                                                                                             , "Phil Wang"                                ,
  "Puppets, sexy, that's me."                                                                                           , "Iain Sterling"                            ,
  "I don't think this is proper cowboy rope."                                                                           , "Ed Gamble"                                ,
  "I've panicked and opened a lemon up."                                                                                , "Ed Gamble"                                ,
  "There's probably a way to get a sofa through a doughnut."                                                            , "Krishnan Guru-Murthy"                     ,
  "It's bamboo o'clock, tick tock."                                                                                     , "Mike Wozniak"                             ,
  "You suck on that and think about things."                                                                            , "Desiree Burch"                            ,
  "I'm gonna do your nipples first, then your face."                                                                    , "Sophie Duker"                             ,
  "Just eat your fucking worm!"                                                                                         , "Bridget Christie"                         ,
  "I think I had pandas in my cooch when I climbed that tree."                                                          , "Sophie Duker"                             ,
  "Papa don’t breach."                                                                                                , "Roisin Conaty"                            ,
  "That potato would have been all rim and bounced out."                                                                , "Doc Brown"                                ,
  "Real gangsters run red lights. You know what I’m saying?"                                                          , "Katherine Ryan"                           ,
  "I’m not going to hoover it off the table like some egg-hungry whore."                                              , "Jon Richardson"                           ,
  "The movement of our potato was crazy smooth."                                                                        , "Doc Brown"                                ,
  "There’s strength in arches."                                                                                       , "Joe Wilkinson"                            ,
  "Bastard’s crying, innit?"                                                                                          , "Paul Chaudry"                             ,
  "Oh, gang."                                                                                                           , "Mel Giedroyc"                             ,
  "Friendship is truth."                                                                                                , "Lolly Adefope"                            ,
  "And then he just stood there, pissing water into a bath while Rome burned."                                          , "Greg Davies"                              ,
  "You bubbly fuck!"                                                                                                    , "Nish Kumar"                               ,
  "Looks like last in PE, first in being a legend!"                                                                     , "Nish Kumar"                               ,
  "Have you ever seen or eaten a wind-dried puffin?"                                                                    , "Bob Mortimer"                             ,
  "Do we strike you?"                                                                                                   , "Bob Mortimer"                             ,
  "Rosalind’s a fucking nightmare!"                                                                                   , "Aisling Bea, Bob Mortimer, Sally Philips" ,
  "I’m a sinner! I have sinned!"                                                                                      , "Bob Mortimer"                             ,
  "Tippety-tapping around like a bloody water boatman."                                                                 , "Liza Tarbuck"                             ,
  "It doesn't matter, sometimes, how ornate the grandfather clock is, the pendulum draws the eye."                      , "Greg Davies"                              ,
  "Just open the box, you pussy!"                                                                                       , "James Acaster"                            ,
  "What happens when you wear long opera gloves and a feather boa to the senior school disco? You do not get fingered." , "Jessica Knappett"                         ,
  "A LIME!"                                                                                                             , "Phil Wang"                                ,
  "That’s the water feature closed for today, kids."                                                                  , "Rhod Gilbert"                             ,
  "The popping candy was lovely but there was a lot of burnt porn."                                                     , "Alex Horne"                               ,
  "Hammering away like an aquatic sewing machine."                                                                      , "Greg Davies"                              ,
  "It stands for ‘bicycle, my excellent bicycle.’"                                                                  , "Joe Thomas"                               ,
  "Am I the spider?"                                                                                                    , "Katherine Parkinson"                      ,
  "I’m sat here between sexy and brainy side and then it’s all chump in the middle."                                , "Nicola Coughlan"                          ,
  "Aaah, you fucking zebra!"                                                                                            , "Sarah Kendall"                            ,
  "I’m tempted to say trust my instincts. But my instincts are telling me to squeak like a bat."                      , "Mike Wozniak"                             ,
  "You’ve got no chutzpah!"                                                                                           , "Mike Wozniak"                             ,
  "Oh, it’s an absolute casserole down there."                                                                        , "Mike Wozniak"                             ,
  "Stop doing the thing I know you’re doing!"                                                                         , "Desiree Birch"                            ,
  "Do you stop when you’ve finished or when you’ve had enough?"                                                     , "Alan Davies"                              ,
  "You know I've just eaten two Creme Eggs and I'm not really up for this."                                             , "Alan Davies",
  "Bicycle, My Excellent Bicycle", "Joe Thomas",
  "Have I met these potatoes before?", "Fern Brady",
  "I cannae, they're COVERED in potatoes!", "Fern Brady",
  "The obvious thing to me was to let the bird fly.", "Fern Brady",
  "Ohh noo!", "Fern Brady",
  "Dafty in the middle.", "Fern Brady",
  "Aren't you from Shrewsbury or something?", "Fern Brady",
  "I'm the Rightful Queen.", "Fern Brady"
) |>
  distinct() |>
  bind_rows(title_pairs) |>
  write_csv("taskmaster_pairs.csv")

reward_links <- c(
  "https://www.instagram.com/p/DTIooKRjkrC/?img_index=1",
  "https://www.instagram.com/p/DS2x4ACDvvz/",
  "https://www.instagram.com/p/DSptN-hjiNy/",
  "https://www.instagram.com/p/DSNqdKbjtzi/",
  "https://www.instagram.com/p/DRjAcIDDfHa/",
  "https://www.instagram.com/p/DQnvM_2jU4O/",
  "https://www.instagram.com/p/DQejRzqDSqt/",
  "https://www.instagram.com/p/DP_4ZU5jcrg/",
  "https://www.instagram.com/p/DPfdo9UjQJh/",
  "https://www.instagram.com/p/DPVSaLlDTRx/",
  "https://www.instagram.com/p/DPRPputDfSm/?img_index=1",
  "https://www.instagram.com/p/DPCyxFDDZLR/?img_index=1",
  "https://www.instagram.com/p/DO3pYFmDTM4/",
  "https://www.instagram.com/p/DOuS_1HjQRR/",
  "https://www.instagram.com/p/DOpHoqEjRdh/",
  "https://www.instagram.com/p/DOTjJAlDUSX/",
  "https://www.instagram.com/p/DOMj-COjnvB/",
  "https://www.instagram.com/p/DN9yTFejaUO/",
  "https://www.instagram.com/p/DNq35_tu1XU/",
  "https://www.instagram.com/p/DNg7ar4NNmZ/",
  "https://www.instagram.com/p/DNdhjebNTHd/",
  "https://www.instagram.com/p/DNVs7PPNng-/",
  "https://www.instagram.com/p/DNPY4NPtBH_/?img_index=1",
  "https://www.instagram.com/p/DNB57qdOxIH/?img_index=1",
  "https://www.instagram.com/p/DM6oVlLtxJn/?img_index=1",
  "https://www.instagram.com/p/DM0oFxSOcdU/",
  "https://www.instagram.com/p/DMwPDwMNGdZ/?img_index=1",
  "https://www.instagram.com/p/DMvNDK3uwn-/",
  "https://www.instagram.com/p/DMjkYcstD_e/",
  "https://www.instagram.com/p/DMRj_QptQgr/",
  "https://www.instagram.com/p/DL-N4I7u7nS/?img_index=1",
  "https://www.instagram.com/p/DL5p5KOuAUG/?img_index=1",
  "https://www.instagram.com/p/DLlIj5Ju24_/?img_index=1",
  "https://www.instagram.com/p/DLd38Uxt0PW/",
  "https://www.instagram.com/p/DLaEkKguDWf/?img_index=1",
  "https://www.instagram.com/p/DLS1AoxuswU/?img_index=1",
  "https://www.instagram.com/p/DLNu0kAO3t4/",
  "https://www.instagram.com/p/DLFjSwyOx3l/?img_index=1",
  "https://www.instagram.com/p/DLBlmV2tplT/",
  "https://www.instagram.com/p/DK7PBBsOvg2/?img_index=1",
  "https://www.instagram.com/p/DK0yXkQNpa8/?img_index=1",
  "https://www.instagram.com/p/DKuNdRJus-2/?img_index=1",
  "https://www.instagram.com/p/DKhlnvMOOfQ/",
  "https://www.instagram.com/p/DKcfuQ1NMFy/",
  "https://www.instagram.com/p/DKWKHK0t6QD/",
  "https://www.instagram.com/p/DKPbRHXNIVI/",
  "https://www.instagram.com/p/DKGkPMINt2I/",
  "https://www.instagram.com/p/DKEFx2DNvja/?img_index=1",
  "https://www.instagram.com/p/DKBORuzNcTs/?img_index=1",
  "https://www.instagram.com/p/DJ3B7sONvOr/",
  "https://www.instagram.com/p/DJz6cAMOAJr/?img_index=1",
  "https://www.instagram.com/p/DJhIvRlRIF9/",
  "https://www.instagram.com/p/DJNvZK2t5LP/?img_index=1",
  "https://www.instagram.com/p/DJGEPNINRNk/?img_index=1",
  "https://www.instagram.com/p/DJDVdOKtfFu/",
  "https://www.instagram.com/p/DI_clkTu-Ne/",
  "https://www.instagram.com/p/DI7dCCftjjv/",
  "https://www.instagram.com/p/DI356qsut1N/",
  "https://www.instagram.com/p/DIoamedu-WD/",
  "https://www.instagram.com/p/DIUs7g_u05w/",
  "https://www.instagram.com/p/DISltqRNE9R/",
  "https://www.instagram.com/p/DH9tLTFtPwz/?img_index=1",
  "https://www.instagram.com/p/DH3SnOnOXf9/",
  "https://www.instagram.com/p/DHv7dwuOgLY/",
  "https://www.instagram.com/p/DHqmwP5u9El/",
  "https://www.instagram.com/p/DHea6q8OHx0/",
  "https://www.instagram.com/p/DHZ08rAtelK/?img_index=1",
  "https://www.instagram.com/p/DG8Xg4wMkps/?img_index=1",
  "https://www.instagram.com/p/DG5rZ_vM1FW/",
  "https://www.instagram.com/p/DGol5oOPwrr/",
  "https://www.instagram.com/p/DGj1EXGsNe_/",
  "https://www.instagram.com/p/DGemBbzsdBo/?img_index=1",
  "https://www.instagram.com/p/DGYSgNBMVC0/",
  "https://www.instagram.com/p/DGJSk3IPWRr/",
  "https://www.instagram.com/p/DF_iWS3sFBa/?img_index=1",
  "https://www.instagram.com/p/DF9MS1vsRpl/",
  "https://www.instagram.com/p/DFy_kUosQ1I/?img_index=1",
  "https://www.instagram.com/p/DFwY8KCMbwt/",
  "https://www.instagram.com/p/DFu_N96Mxl7/",
  "https://www.instagram.com/p/DFrZA4mMKO3/",
  "https://www.instagram.com/p/DFosbUMMDIi/",
  "https://www.instagram.com/p/DFl72BdsCSO/",
  "https://www.instagram.com/p/DFjR4hgMvau/",
  "https://www.instagram.com/p/DFgZ_pCvxki/",
  "https://www.instagram.com/p/DFb23D4MZXZ/",
  "https://www.instagram.com/p/DFWWukCsJWe/",
  "https://www.instagram.com/p/DFUBjTgsoqx/",
  "https://www.instagram.com/p/DFOptYdswMy/",
  "https://www.instagram.com/p/DFL-l84MYg4/",
  "https://www.instagram.com/p/DFIvmtVP1Uk/",
  "https://www.instagram.com/p/DFGIBGwPBiZ/",
  "https://www.instagram.com/p/DEp2p8aPHsg/",
  "https://www.instagram.com/p/DDgKgD2MlGI/",
  "https://www.instagram.com/p/DDUnP35vLYZ/",
  "https://www.instagram.com/p/DC61NyUpPhL/",
  "https://www.instagram.com/p/DC0mbzjsoic/",
  "https://www.instagram.com/p/DCuStBHvCmM/",
  "https://www.instagram.com/p/DCDXn9kMxSw/",
  "https://www.instagram.com/p/DBczKQmMOcV/",
  "https://www.instagram.com/p/DBZCU1ePPs-/",
  "https://www.instagram.com/p/DBEjsTxvb41/?img_index=1",
  "https://www.instagram.com/p/DA_MKn5PjI_/",
  "https://www.instagram.com/p/DAgck93P7j0/",
  "https://www.instagram.com/p/C_V4fcyPThE/",
  "https://www.instagram.com/p/C-_xeKbMplt/",
  "https://www.instagram.com/p/C8-_MZysGFk/",
  "https://www.instagram.com/p/C806SeWsUFh/",
  "https://www.instagram.com/p/C7XouIbshaq/",
  "https://www.instagram.com/p/C6l_DM1rFOd/",
  "https://www.instagram.com/p/C5e3J2jMhi2/",
  "https://www.instagram.com/p/C5JdXDNJDpV/?img_index=1",
  "https://www.instagram.com/p/C4WOVgjP-ZX/",
  "https://www.instagram.com/p/C4B9hqnMzFU/",
  "https://www.instagram.com/p/C362A84Mf9S/",
  "https://www.instagram.com/p/C2U8nofMT6u/",
  "https://www.instagram.com/p/C2JPWnjswGc/",
  "https://www.instagram.com/p/C13Q02VM78f/",
  "https://www.instagram.com/p/C0-b3nAsJ8P/",
  "https://www.instagram.com/p/C0z34HEs16C/",
  "https://www.instagram.com/p/C0k-15ds9oA/",
  "https://www.instagram.com/p/Cz6RHjmsgtf/",
  "https://www.instagram.com/p/CzZ6wlDMt5s/",
  "https://www.instagram.com/p/CzRWbSTL_C5/",
  "https://www.instagram.com/p/CyoboVJPnoN/",
  "https://www.instagram.com/p/CyJJ1ZlMhk6/",
  "https://www.instagram.com/p/Cx9pMrKsUrI/",
  "https://www.instagram.com/p/Cx0Tg0GuqEq/",
  "https://www.instagram.com/p/CxlJ5dnMtlD/",
  "https://www.instagram.com/p/CxWCnPkvDrW/",
  "https://www.instagram.com/p/Cwc-ik2szwp/",
  "https://www.instagram.com/p/CwYC6_xrYhW/",
  "https://www.instagram.com/p/Cv2wnmgvMr4/",
  "https://www.instagram.com/p/CvKrh9wsq59/",
  "https://www.instagram.com/p/CuHqGxDrHHl/",
  "https://www.instagram.com/p/Ct8BTlRs529/",
  "https://www.instagram.com/p/CtmSzzrreGC/",
  "https://www.instagram.com/p/CsgkOS_MQXC/",
  "https://www.instagram.com/p/CsNS6azMNOR/",
  "https://www.instagram.com/p/CruIPuEsD60/",
  "https://www.instagram.com/p/CrmO4Kcsmm0/",
  "https://www.instagram.com/p/CrfFlHFMR7j/",
  "https://www.instagram.com/p/CrMR2U1P5Ha/",
  "https://www.instagram.com/p/CrCIDCivv4N/",
  "https://www.instagram.com/p/CqqKgnruuIW/",
  "https://www.instagram.com/p/CqS2zuMMJYt/",
  "https://www.instagram.com/p/CpwDEd8s_yW/",
  "https://www.instagram.com/p/CpQVxMCJitY/",
  "https://www.instagram.com/p/CoTH9ZrMjup/",
  "https://www.instagram.com/p/CoLRUlWvw9W/",
  "https://www.instagram.com/p/CnxE8HWph4n/",
  "https://www.instagram.com/p/CnbAKWvLHPj/",
  "https://www.instagram.com/p/CnX7RapPVUp/",
  "https://www.instagram.com/p/CnVaFtlszUa/",
  "https://www.instagram.com/p/Cm5nMirM1NL/",
  "https://www.instagram.com/p/Cmx-FP8MPde/",
  "https://www.instagram.com/p/Cmp-P5WML0t/",
  "https://www.instagram.com/p/CmjnTPgu600/",
  "https://www.instagram.com/p/Cmf508PsWeW/",
  "https://www.instagram.com/p/Cl5OCHIspKF/",
  "https://www.instagram.com/p/ClFesQ1LVt8/",
  "https://www.instagram.com/p/Ck6VkL0PpCV/",
  "https://www.instagram.com/p/CkzIoZjMx1f/",
  "https://www.instagram.com/p/CkruJRJM2LR/?img_index=1",
  "https://www.instagram.com/p/CkLhK0QMVgV/",
  "https://www.instagram.com/p/Cj6khC2MtyR/",
  "https://www.instagram.com/p/CjMY71kMEKF/",
  "https://www.instagram.com/p/CjKMlZfshPh/",
  "https://www.instagram.com/p/CjHgFPiMm2_/",
  "https://www.instagram.com/p/CjEmOsYsXf4/",
  "https://www.instagram.com/p/Ci-PQA-M1AW/",
  "https://www.instagram.com/p/CinCdooOeBz/",
  "https://www.instagram.com/p/ChaasD_v6N4/",
  "https://www.instagram.com/p/ChRBsXXuolT/",
  "https://www.instagram.com/p/ChG-pmMuIDW/",
  "https://www.instagram.com/p/ChAekWmJmGA/",
  "https://www.instagram.com/p/CgZrYnaLkzR/",
  "https://www.instagram.com/p/CgM8GE1LC9p/",
  "https://www.instagram.com/p/CfwnuTMu6d_/",
  "https://www.instagram.com/p/CfjwmeIJBoU/",
  "https://www.instagram.com/p/CfdSUdkslr8/",
  "https://www.instagram.com/p/Cfaso0jMlkM/",
  "https://www.instagram.com/p/CfJ6YEcrOC2/",
  "https://www.instagram.com/p/CfDmGCbsnBp/",
  "https://www.instagram.com/p/Cev8Np6OIBd/",
  "https://www.instagram.com/p/Cd3soXWJ9Ia/",
  "https://www.instagram.com/p/CdzYVJSsF-_/",
  "https://www.instagram.com/p/CdSJy1JMKD8/",
  "https://www.instagram.com/p/CdNCoqjMQFU/",
  "https://www.instagram.com/p/CdI5guaMoxL/",
  "https://www.instagram.com/p/CdBM0Oqsfwi/",
  "https://www.instagram.com/p/Cc62Ie2r3R4/",
  "https://www.instagram.com/p/Cc4a4D9Mtvi/",
  "https://www.instagram.com/p/CcxvWuzMdDv/",
  "https://www.instagram.com/p/CcRcVYtMnf-/",
  "https://www.instagram.com/p/CcJ66ALMUpO/",
  "https://www.instagram.com/p/CbWWCc1LQDi/",
  "https://www.instagram.com/p/CbJzL9WM7Sv/",
  "https://www.instagram.com/p/CbG3ob6MJU2/",
  "https://www.instagram.com/p/Ca2XLNgl_ZN/",
  "https://www.instagram.com/p/CauduQrO0Ie/",
  "https://www.instagram.com/p/CZ3bPbeMPrI/",
  "https://www.instagram.com/p/CZOH16eMgTr/",
  "https://www.instagram.com/p/CZAB8x4FXQv/",
  "https://www.instagram.com/p/CYLZxJvMPPA/",
  "https://www.instagram.com/p/CYDPMausLOA/"
) |>
  str_remove("\\?img_index=\\d") |>
  str_c("embed")

str_c(
  '<iframe src="',
  reward_links,
  '"width="400" height="480" frameborder="0" scrolling="no"></iframe>'
) |>
  write_lines("reward.txt")
